apiVersion: v1
kind: Service
metadata:
  name: audio-stream-websocket
  labels:
    app: audio-stream-websocket
spec:
  type: LoadBalancer
  sessionAffinity: ClientIP
  ports:
  - port: 80
    targetPort: 8765
    protocol: TCP
    name: websocket
  selector:
    app: audio-stream-websocket

